### ISSUE TITLE
[feature-request] Группировка моков

### ISSUE THREAD

**Issue by Bizunow** [avivasyuta/mockiato#33]
Иногда есть необходимость замокать сразу несколько запросов, например 3-5 штук.
В таком случае, хочется объединить эти моки в одну группу с определенным именем.
Пример того, как хотелось бы:

```
--- Моки для воспроизведения бага в настройках юзера
    - /user/settings
    - /user/profile
    - /uesr/balance

--- Моки для локальной разработки
    - mock1
    ...
    - mockN
```

**Comment by avivasyuta** [comment]
Hello, thanks for the feature request. This is a great idea. I'm already working on implementation.

**Comment by avivasyuta** [comment]
Feature added in version 1.7.0
